{
  "ID": "39a676e8-4916-4942-a1ec-5020702b7db9",
  "Root": {
    "alive": true,
    "content": [
      "b66cda9c-f3d3-4327-b800-e6c2911c204f",
      "26cf1cfe-b697-4efc-8ba5-fda6f03e2555",
      "c4931d18-022d-4d35-9d4f-33a624d9d8b7",
      "257f247a-42a3-4260-9b8a-0739c6017e58",
      "eac6f2f7-4f00-4a8d-aab7-9f35fdae4f54",
      "e4712de1-5b0a-4b62-9003-7c31831b8b17",
      "fa6b55d0-9e4f-4cd3-b75c-1d0c677685ee",
      "da8de6d3-a3ba-47a1-949b-040d01c9b421",
      "309a6c52-997a-4192-8fbe-50a13d8e55fb",
      "ff5f1237-6dab-4168-b640-48336e5ea8f8",
      "b8a37e22-02c3-43ab-86b9-ff7ec4ddc15f",
      "76e2d2f8-5caf-4b10-ba39-e453f6c015c3",
      "f3908a1f-fb5e-452a-8f0e-49446f7b23a6"
    ],
    "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "created_time": 1550460060000,
    "format": {
      "page_full_width": true,
      "page_small_text": true
    },
    "id": "39a676e8-4916-4942-a1ec-5020702b7db9",
    "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "last_edited_time": 1550460360000,
    "parent_id": "d37cda98-a070-46f6-b2cc-375731ea3bdb",
    "parent_table": "block",
    "permissions": [
      {
        "role": "editor",
        "type": "user_permission",
        "user_id": "bb760e2d-d679-4b64-b2a9-03005b21870a"
      }
    ],
    "properties": {
      "title": [
        [
          "Exceptions"
        ]
      ]
    },
    "type": "page",
    "version": 37,
    "content_resolved": [
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460107607,
        "id": "b66cda9c-f3d3-4327-b800-e6c2911c204f",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460107607,
        "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "000 Exceptions and exception handling"
            ]
          ]
        },
        "type": "page",
        "version": 1,
        "title": "000 Exceptions and exception handling"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460108273,
        "id": "26cf1cfe-b697-4efc-8ba5-fda6f03e2555",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460108273,
        "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "010 Catching an exception with try-catch"
            ]
          ]
        },
        "type": "page",
        "version": 1,
        "title": "010 Catching an exception with try-catch"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460109208,
        "id": "c4931d18-022d-4d35-9d4f-33a624d9d8b7",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460109208,
        "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "020 The try-with-resources statement"
            ]
          ]
        },
        "type": "page",
        "version": 1,
        "title": "020 The try-with-resources statement"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460111030,
        "id": "257f247a-42a3-4260-9b8a-0739c6017e58",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460111030,
        "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "030 Custom Exceptions"
            ]
          ]
        },
        "type": "page",
        "version": 1,
        "title": "030 Custom Exceptions"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460112121,
        "id": "eac6f2f7-4f00-4a8d-aab7-9f35fdae4f54",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460112121,
        "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "040 Handling InterruptedException"
            ]
          ]
        },
        "type": "page",
        "version": 1,
        "title": "040 Handling InterruptedException"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460113354,
        "id": "e4712de1-5b0a-4b62-9003-7c31831b8b17",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460113354,
        "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "050 Return statements in try catch block"
            ]
          ]
        },
        "type": "page",
        "version": 1,
        "title": "050 Return statements in try catch block"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460114233,
        "id": "fa6b55d0-9e4f-4cd3-b75c-1d0c677685ee",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460114233,
        "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "060 Introduction"
            ]
          ]
        },
        "type": "page",
        "version": 1,
        "title": "060 Introduction"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460115171,
        "id": "da8de6d3-a3ba-47a1-949b-040d01c9b421",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460115171,
        "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "070 The Java Exception Hierarchy - Unchecked and Checked Exceptions"
            ]
          ]
        },
        "type": "page",
        "version": 1,
        "title": "070 The Java Exception Hierarchy - Unchecked and Checked Exceptions"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460116211,
        "id": "309a6c52-997a-4192-8fbe-50a13d8e55fb",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460116211,
        "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "080 Creating and reading stacktraces"
            ]
          ]
        },
        "type": "page",
        "version": 1,
        "title": "080 Creating and reading stacktraces"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460117282,
        "id": "ff5f1237-6dab-4168-b640-48336e5ea8f8",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460117282,
        "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "090 Throwing an exception"
            ]
          ]
        },
        "type": "page",
        "version": 1,
        "title": "090 Throwing an exception"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460118333,
        "id": "b8a37e22-02c3-43ab-86b9-ff7ec4ddc15f",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460118333,
        "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "100 Advanced features of Exceptions"
            ]
          ]
        },
        "type": "page",
        "version": 1,
        "title": "100 Advanced features of Exceptions"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460119324,
        "id": "76e2d2f8-5caf-4b10-ba39-e453f6c015c3",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460119324,
        "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "110 The try-finally and try-catch-finally statements"
            ]
          ]
        },
        "type": "page",
        "version": 1,
        "title": "110 The try-finally and try-catch-finally statements"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460120142,
        "id": "f3908a1f-fb5e-452a-8f0e-49446f7b23a6",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460120142,
        "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "120 The throws clause in a method declaration"
            ]
          ]
        },
        "type": "page",
        "version": 1,
        "title": "120 The throws clause in a method declaration"
      }
    ],
    "title": "Exceptions",
    "format_page": {
      "page_cover": "",
      "page_cover_position": 0,
      "page_font": "",
      "page_full_width": true,
      "page_icon": "",
      "page_small_text": true
    }
  },
  "Users": [
    {
      "email": "kkowalczyk@gmail.com",
      "family_name": "Kowalczyk",
      "given_name": "Krzysztof",
      "id": "bb760e2d-d679-4b64-b2a9-03005b21870a",
      "locale": "en",
      "mobile_onboarding_completed": true,
      "onboarding_completed": true,
      "profile_photo": "https://s3-us-west-2.amazonaws.com/public.notion-static.com/2dcaa66c-7674-4ff6-9924-601785b63561/head-bw-640x960.png",
      "time_zone": "America/Los_Angeles",
      "version": 18
    }
  ],
  "Tables": null
}