{
  "ID": "e4712de1-5b0a-4b62-9003-7c31831b8b17",
  "Root": {
    "alive": true,
    "content": [
      "cdfe5a0c-bb8c-4f3e-a22e-c66cff4b66ff",
      "25b6760c-eafa-48a7-81a5-131ef105ad69",
      "cdc794ef-1849-40cf-b068-2713d643339d",
      "67e54e13-ff9b-4431-879d-0eddc1e7aed3",
      "6fa8bae9-e5ce-4e51-b5d6-8f839d3d5a6b",
      "103418cd-ca27-49de-af92-2149fd84de6a"
    ],
    "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "created_time": 1550460113354,
    "id": "e4712de1-5b0a-4b62-9003-7c31831b8b17",
    "ignore_block_count": true,
    "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "last_edited_time": 1550460113354,
    "parent_id": "39a676e8-4916-4942-a1ec-5020702b7db9",
    "parent_table": "block",
    "properties": {
      "title": [
        [
          "050 Return statements in try catch block"
        ]
      ]
    },
    "type": "page",
    "version": 1,
    "content_resolved": [
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460113353,
        "id": "cdfe5a0c-bb8c-4f3e-a22e-c66cff4b66ff",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460113353,
        "parent_id": "e4712de1-5b0a-4b62-9003-7c31831b8b17",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "Although it’s bad practice, it’s possible to add multiple return statements in a exception handling block:"
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "Although it’s bad practice, it’s possible to add multiple return statements in a exception handling block:"
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460113353,
        "id": "25b6760c-eafa-48a7-81a5-131ef105ad69",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460113353,
        "parent_id": "e4712de1-5b0a-4b62-9003-7c31831b8b17",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "Plain Text"
            ]
          ],
          "title": [
            [
              "public static int returnTest(int number){\n   try{\n       if(number%2 == 0) throw new Exception(\"Exception thrown\");\n       else return x;\n   }\n   catch(Exception e){\n       return 3;\n   }\n   finally{\n       return 7;\n   }\n}"
            ]
          ]
        },
        "type": "code",
        "version": 1,
        "code": "public static int returnTest(int number){\n   try{\n       if(number%2 == 0) throw new Exception(\"Exception thrown\");\n       else return x;\n   }\n   catch(Exception e){\n       return 3;\n   }\n   finally{\n       return 7;\n   }\n}",
        "code_language": "Plain Text"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460113354,
        "id": "cdc794ef-1849-40cf-b068-2713d643339d",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460113354,
        "parent_id": "e4712de1-5b0a-4b62-9003-7c31831b8b17",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "This method will always return 7 since the finally block associated with the try/catch block is executed before anything is returned. Now, as finally has "
            ],
            [
              "return 7;",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              ", this value supersedes the try/catch return values."
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "This method will always return 7 since the finally block associated with the try/catch block is executed before anything is returned. Now, as finally has "
          },
          {
            "Text": "return 7;",
            "AttrFlags": 2
          },
          {
            "Text": ", this value supersedes the try/catch return values."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460113354,
        "id": "67e54e13-ff9b-4431-879d-0eddc1e7aed3",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460113354,
        "parent_id": "e4712de1-5b0a-4b62-9003-7c31831b8b17",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "If the catch block returns a primitive value and that primitive value is subsequently changed in the finally block, the value returned in the catch block will be returned and the changes from the finally block will be ignored."
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "If the catch block returns a primitive value and that primitive value is subsequently changed in the finally block, the value returned in the catch block will be returned and the changes from the finally block will be ignored."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460113354,
        "id": "6fa8bae9-e5ce-4e51-b5d6-8f839d3d5a6b",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460113354,
        "parent_id": "e4712de1-5b0a-4b62-9003-7c31831b8b17",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "The example below will print “0”, not “1”."
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "The example below will print “0”, not “1”."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550460113354,
        "id": "103418cd-ca27-49de-af92-2149fd84de6a",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550460113354,
        "parent_id": "e4712de1-5b0a-4b62-9003-7c31831b8b17",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "Plain Text"
            ]
          ],
          "title": [
            [
              "public class FinallyExample {\n\n    public static void main(String[] args) {\n        int n = returnTest(4);\n        \n        System.out.println(n);\n    }\n\n    public static int returnTest(int number) {\n        \n        int returnNumber = 0; \n        \n        try {\n            if (number % 2 == 0)\n                throw new Exception(\"Exception thrown\");\n            else\n                return returnNumber;\n        } catch (Exception e) {\n            return returnNumber;\n        } finally {\n            returnNumber = 1;\n        }\n    }\n}"
            ]
          ]
        },
        "type": "code",
        "version": 1,
        "code": "public class FinallyExample {\n\n    public static void main(String[] args) {\n        int n = returnTest(4);\n        \n        System.out.println(n);\n    }\n\n    public static int returnTest(int number) {\n        \n        int returnNumber = 0; \n        \n        try {\n            if (number % 2 == 0)\n                throw new Exception(\"Exception thrown\");\n            else\n                return returnNumber;\n        } catch (Exception e) {\n            return returnNumber;\n        } finally {\n            returnNumber = 1;\n        }\n    }\n}",
        "code_language": "Plain Text"
      }
    ],
    "title": "050 Return statements in try catch block"
  },
  "Users": [
    {
      "email": "kkowalczyk@gmail.com",
      "family_name": "Kowalczyk",
      "given_name": "Krzysztof",
      "id": "bb760e2d-d679-4b64-b2a9-03005b21870a",
      "locale": "en",
      "mobile_onboarding_completed": true,
      "onboarding_completed": true,
      "profile_photo": "https://s3-us-west-2.amazonaws.com/public.notion-static.com/2dcaa66c-7674-4ff6-9924-601785b63561/head-bw-640x960.png",
      "time_zone": "America/Los_Angeles",
      "version": 18
    }
  ],
  "Tables": null
}